services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image : node:24-alpine3.21
    container_name: node_backend
    restart: always
    working_dir: /app
    volumes:
      - ./.env:/app
      - ./backend:/app
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run start
    
  frontend:
    image: nginx:alpine
    container_name: static_frontend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
