services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    image : node:24-alpine3.21
    container_name: node_backend
    restart: always
    working_dir: /app
    volumes:
      - ./.env:/app
      - ./backend:/app
    env_file: .env
    ports:
      - "3002:3000"
    depends_on:
      - db
    command: sh -c "npm i && npm run start"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: static_frontend
    restart: always
    env_file: .env
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  db_data:
